server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:log4jdbc:h2:mem:testdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 5000
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: none
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: hoon.model
  configuration:
    map-underscore-to-camel-case: true
debug: true
logging:
  level: debug